# Generated by Django 4.2.15 on 2024-09-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_laptops',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=320, null=True)),
                ('brand', models.CharField(blank=True, choices=[('dell', 'Dell'), ('lenovo', 'Lenovo'), ('asus', 'Asus'), ('aser', 'Aser'), ('Fojisto', 'fojisto'), ('macbook', 'Apple Macbook'), ('microsoft', 'Microsoft')], max_length=220, null=True)),
                ('ussing_status', models.CharField(choices=[('used', 'Used'), ('new', 'New'), ('stock', 'Stock')], max_length=220)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('offer', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpu_model', models.CharField(max_length=220)),
                ('ram_model', models.CharField(max_length=220)),
                ('graphic_model', models.CharField(max_length=220)),
                ('hard_model', models.CharField(max_length=220)),
                ('monitor_model', models.CharField(max_length=220)),
                ('body_issues', models.CharField(default=None, max_length=220, null=True)),
                ('weak_points', models.CharField(max_length=220)),
                ('images', models.ImageField(blank=True, upload_to='media/stock_laptop/%Y/%m/%d')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
