# Generated by Django 4.2.15 on 2024-09-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_laptops',
            name='images',
            field=models.ImageField(blank=True, upload_to='stock_laptop/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='stock_laptops',
            name='ussing_status',
            field=models.CharField(choices=[('used', 'کارکرده'), ('new', 'تازه'), ('stock', 'استوک')], max_length=220),
        ),
    ]
