# Generated by Django 4.2.15 on 2024-09-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_stock_laptops_ussing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_laptops',
            name='ussing_status',
            field=models.CharField(choices=[('used', 'Used'), ('new', 'New'), ('stock', 'Stock')], max_length=220),
        ),
    ]
