# Generated by Django 4.2.15 on 2024-09-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_stock_laptops_ussing_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock_laptops',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='stock_laptops',
            name='ussing_status',
            field=models.CharField(choices=[('used', 'کارکرده'), ('new', 'تازه'), ('stock', 'استوک')], max_length=220),
        ),
    ]
